### ISSUE TITLE
shara_data HTML counterpart is not displayed

### ISSUE THREAD

**Issue by SebZiHub** [ea-foundation/raise#22]
**Current situation:**
In the configuration JSON, the share_data element is placed and configured as follow:
![image](https://user-images.githubusercontent.com/19263542/73477898-5c8aa680-4395-11ea-8dcb-c5918a2b5352.png)

![image](https://user-images.githubusercontent.com/19263542/73478039-9cea2480-4395-11ea-8d04-34afbbffd8ba.png)

In the created form, the fields look like this:

![image](https://user-images.githubusercontent.com/19263542/73478161-d9b61b80-4395-11ea-9eab-818d8d550622.png)

**Expected behavior:**
With the settings configured as above, I expected a checkbox with the corresponding label, with a placement somewhere near the existing checkbox.

**Comment by naokipeter** [comment]
For the newsletter checkbox to show up, you need to define at least one webhook endpoint that forwards the user's email to the mailing list platform.

```
"webhook": {
  "mailing_list": {
    "live": [
      "https://hooks.zapier.com/hooks/catch/something"
    ]
  }
}
```

If you want to change the label text, you can do so inside `form_elements`

```
"form_elements": {
  "mailing_list": {
    "en": "Subscribe me to special updates.",
    "de": "Spezial-Updates abonnieren."
  }
}
```

We'll add this to the README in the coming weeks.

**Comment by SebZiHub** [comment]
Thanks for the quick heads up. Adding the the `webhook > mailing_list > live` and `form_elements > mailing_list` elements in the configuration did it. Desired behavior achieved, thanks.
