### ISSUE TITLE
details for bank transfer are not translated

### ISSUE THREAD

**Issue by SebZiHub** [ea-foundation/raise#23]
**Current situation:**
A bank transfer is configured. In the user's browser, the language is recognized and steps, amount of donation, further hints, success message etc. are properly translated. The bank transfer details are displayed in English:
![image](https://user-images.githubusercontent.com/19263542/73478822-12a2c000-4397-11ea-93dd-1f6bf88dae8b.png)

the configuration beeing:
![image](https://user-images.githubusercontent.com/19263542/73478954-4978d600-4397-11ea-95b5-92341a4fa572.png)

**Expected behavior:**
The details for the bank transfer appear in German too, e.g. "Begünstigter", "Kontonummer" and "Zweck"

**Comment by naokipeter** [comment]
The automatic label translation from English to German seems to be broken when you do not use JsonLogic. As a work-around you can use German labels directly in the config. If your site is monolignual, this should work fine.

**Comment by SebZiHub** [comment]
Thanks a lot Naoki. I modified the configuration as follow:
![image](https://user-images.githubusercontent.com/19263542/73481364-010fe700-439c-11ea-83c4-daf6d75123dc.png)

and the result was:

![image](https://user-images.githubusercontent.com/19263542/73481406-1127c680-439c-11ea-8fa5-4db981812b99.png)

The site is monolingual so with this workaround the situation is OK. Thanks for the quick reply.

**Comment by naokipeter** [comment]
Fixed in https://github.com/ea-foundation/raise/commit/fa7cf0ee3dee65cfcf890acc46b957085ce62330
